# Generated by Django 4.2.7 on 2025-08-23 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('highlights', models.TextField(help_text='Key achievements and successes this week')),
                ('pendings', models.TextField(blank=True, help_text='Tasks and items that are still pending or in progress')),
                ('challenges', models.TextField(blank=True, help_text='Obstacles, issues, or difficulties encountered')),
                ('personal_updates', models.TextField(blank=True, help_text='Personal professional development or updates')),
                ('strategies', models.TextField(blank=True, help_text='Plans, strategies, and next steps for upcoming period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journal.department')),
            ],
            options={
                'verbose_name': 'Weekly Journal Entry',
                'verbose_name_plural': 'Weekly Journal Entries',
                'ordering': ['-date_from', '-created_at'],
                'unique_together': {('author', 'date_from', 'date_to')},
            },
        ),
        migrations.CreateModel(
            name='JournalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journal.weeklyjournal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
