# Generated by Django 4.2.7 on 2025-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyjournal',
            name='challenges',
            field=models.JSONField(blank=True, default=list, help_text='Obstacles, issues, or difficulties encountered'),
        ),
        migrations.AlterField(
            model_name='weeklyjournal',
            name='highlights',
            field=models.JSONField(default=list, help_text='Key achievements and successes this week'),
        ),
        migrations.AlterField(
            model_name='weeklyjournal',
            name='pendings',
            field=models.JSONField(blank=True, default=list, help_text='Tasks and items that are still pending or in progress'),
        ),
        migrations.AlterField(
            model_name='weeklyjournal',
            name='personal_updates',
            field=models.JSONField(blank=True, default=list, help_text='Personal professional development or updates'),
        ),
        migrations.AlterField(
            model_name='weeklyjournal',
            name='strategies',
            field=models.JSONField(blank=True, default=list, help_text='Plans, strategies, and next steps for upcoming period'),
        ),
    ]
