# Generated by Django 4.2.7 on 2025-08-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_weeklyjournal_challenges_and_more'),
    ]

    operations = [
    ]
