# Generated by Django 4.2.7 on 2025-08-24 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_auto_20250823_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopManagementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Top Management Weekly Report', max_length=200)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('admin_highlights', models.JSONField(blank=True, default=list, help_text='Additional highlights added directly by admin')),
                ('admin_challenges', models.JSONField(blank=True, default=list, help_text='Additional challenges added directly by admin')),
                ('admin_strategies', models.JSONField(blank=True, default=list, help_text='Additional strategies added directly by admin')),
                ('executive_summary', models.TextField(blank=True, help_text='Executive summary for top management')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Top Management Report',
                'verbose_name_plural': 'Top Management Reports',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='TopManagementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('highlights', 'Highlights'), ('pendings', 'Pendings'), ('challenges', 'Challenges'), ('personal_updates', 'Personal Updates'), ('strategies', 'Strategies')], max_length=20)),
                ('item_index', models.IntegerField(help_text='Index of the item within the section')),
                ('item_text', models.TextField(help_text='Cached text of the tagged item')),
                ('item_status', models.CharField(help_text='Cached status of the tagged item', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text="Optional note from admin about this item's importance")),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topman_tags', to='journal.weeklyjournal')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='journal.topmanagementreport')),
                ('tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Top Management Tag',
                'verbose_name_plural': 'Top Management Tags',
                'ordering': ['-priority', '-tagged_at'],
                'unique_together': {('journal_entry', 'section', 'item_index', 'report')},
            },
        ),
    ]
